# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-13 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='portfoio_site',
            new_name='portfolio_site',
        ),
    ]
